sonar.projectKey=EL-BID_Evaluacion-de-nivel-de-madurez-Smart
sonar.projectName=Evaluacion-de-nivel-de-madurez-Smart

# Source code
sonar.sources=.

# Common exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/target/**,**/*.min.js,**/vendor/**,**/__pycache__/**,**/*.pyc,**/venv/**,**/.venv/**,**/coverage/**

# SCM
sonar.scm.provider=git